---

- name: RedHat | Install packages
  yum: >
    name={{ item }}
    state=installed
  with_items: php.packages

- name: RedHat | Global php.ini file
  template: >
    src="php.ini.j2"
    dest="{{ php.conf_root }}/php.ini"

# vim: syntax=ansible ts=2 sw=2 sts=2 sr et
